"use client";

import { Container } from "./ui/container";
import { Shield, Search, RefreshCw, Database, Lightbulb, BarChart } from "lucide-react";
import { motion } from "framer-motion";

const features = [
  {
    name: "Advanced Plagiarism Detection",
    description: "Compare documents against billions of web pages, academic journals, and publications to identify potential plagiarism.",
    icon: Search,
  },
  {
    name: "AI Content Recognition",
    description: "Cutting-edge algorithms detect content generated by AI tools like ChatGPT, Claude, Bard, and more.",
    icon: Lightbulb,
  },
  {
    name: "Real-time Scanning",
    description: "Upload and scan documents in real-time with fast processing and immediate results.",
    icon: RefreshCw,
  },
  {
    name: "Comprehensive Reports",
    description: "Receive detailed reports highlighting problematic sections with similarity scores and source references.",
    icon: BarChart,
  },
  {
    name: "Secure Document Handling",
    description: "Your documents remain private and secure with enterprise-grade encryption and data protection.",
    icon: Shield,
  },
  {
    name: "Extensive Database",
    description: "Access our continuously updated database of academic papers, publications, and web content.",
    icon: Database,
  },
];

export function Features() {
  return (
    <div id="features" className="py-24 sm:py-32 bg-white dark:bg-gray-950">
      <Container>
        <div className="mx-auto max-w-2xl md:text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl mb-3">
            Advanced Features for Complete Protection
          </h2>
          <p className="text-lg text-muted-foreground">
            Piracy Fighter combines the most powerful detection technologies to safeguard your intellectual property.
          </p>
        </div>
        
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
            {features.map((feature, index) => (
              <motion.div 
                key={feature.name}
                className="flex flex-col"
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
              >
                <dt className="flex items-center gap-x-3 text-base font-semibold leading-7">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-100 dark:bg-blue-900/30">
                    <feature.icon className="h-6 w-6 text-blue-600" aria-hidden="true" />
                  </div>
                  {feature.name}
                </dt>
                <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-muted-foreground">
                  <p className="flex-auto">{feature.description}</p>
                </dd>
              </motion.div>
            ))}
          </dl>
        </div>
      </Container>
    </div>
  );
} 